# CSP: IMPLEMENTS A REPRESENTATION OF A CONSTRAINT SATISFACTION PROBLEM. THE CSP IS DEFINED BY ITS VARIABLES, DOMAINS, NEIGHBOURS, CONSTRAINTS. IN A CSP, THE GOAL IS TO FIND AN ASSIGNMENT OF VALUES TO THE VARIABLES THAT SATISFIES ALL OF THE CONSTRAINTS.
class CSP:
    def __init__(self, VARIABLES, DOMAINS, CONSTRAINTS):
        self.VARIABLES = VARIABLES  # LIST OF VARIABLES
        self.DOMAINS = DOMAINS  # DICTIONARY OF DOMAINS: THE KEYS OF THE DICTIONARY ARE THE VARIABLES. THE VALUE OF EACH KEY IN THE DICTIONARY IS THE LIST OF VALUES OF THAT VARIABLE. THE VALUES OF A VARIABLE ARE THE VALUES THAT THE VARIABLE CAN TAKE.
        # LIST OF CONSTRAINTS: THE CONSTRAINT VARIABLE IS DEFINED BY A LISTS OF TWO TUPLES (PAIRS). EACH TUPLE REPRESENTS A PAIR OF VARIABLES THAT MUST SATISFY THE CONSTRAINT. THE CONSTRAINT IS SATISFIED IF THE PAIR DOES NOT HAVE THE SAME VALUE.
        self.CONSTRAINTS = CONSTRAINTS
        self.NEIGHBOURS = {}  # DICTIONARY OF NEIGHBOURS: THE KEY OF THE DICTIONARY IS THE VARIABLE. THE VALUE OF THE DICTIONARY IS THE LIST OF NEIGHBOURS OF THE VARIABLE. THE NEIGHBOURS OF A VARIABLE ARE THE VARIABLES THAT SHARE A CONSTRAINT WITH THE VARIABLE.
        # FOR EACH VARIABLE, FIND THE NEIGHBOURS OF THE VARIABLE.
        for VARIABLE in self.VARIABLES:
            # INITIALIZE THE LIST OF NEIGHBOURS OF THE VARIABLE.
            self.NEIGHBOURS[VARIABLE] = []
            # FOR EACH CONSTRAINT, FIND THE NEIGHBOURS OF THE VARIABLE.
            for CONSTRAINT in self.CONSTRAINTS:
                # IF THE VARIABLE IS INVOLVED IN THE CONSTRAINT, FIND THE NEIGHBOURS OF THE VARIABLE.
                if VARIABLE in CONSTRAINT:
                    # FOR EACH VARIABLE INVOLVED IN THE CONSTRAINT, FIND THE NEIGHBOURS OF THE VARIABLE.
                    for VARIABLE_2 in CONSTRAINT:
                        # IF THE THEY ARE NOT THE SAME VARIABLE, ADD THE VARIABLE TO THE LIST OF NEIGHBOURS OF THE VARIABLE.
                        if VARIABLE_2 != VARIABLE:
                            # ADD THE VARIABLE TO THE LIST OF NEIGHBOURS OF THE VARIABLE.
                            self.NEIGHBOURS[VARIABLE].append(VARIABLE_2)
