# ISOTONIC_REGRESSION: IMPLEMENTATION OF ISOTONIC REGRESSION. IN STATISTICS AND NUMERICAL ANALYSIS, ISOTONIC REGRESSION OR MONOTONIC REGRESSION IS THE TECHNIQUE OF FITTING A FREE-FORM LINE TO A SEQUENCE OF OBSERVATIONS SUCH THAT THE FITTED LINE IS NON-DECREASING (OR NON-INCREASING) EVERYWHERE, AND LIES AS CLOSE TO THE OBSERVATIONS AS POSSIBLE.
class ISOTONIC_REGRESSION:
    # INITIALIZES THE ISOTONIC REGRESSION MODEL
    def __init__(self):
        pass