import numpy as np

# TODO

# LEAST_ANGLE_REGRESSION: IMPLEMENTATION OF LEAST ANGLE REGRESSION. LEAST ANGLE REGRESSION (LARS) IS A REGRESSION ALGORITHM FOR HIGH-DIMENSIONAL DATA. LARS IS SIMILAR TO FORWARD STEPWISE REGRESSION, BUT INSTEAD OF INCLUDING VARIABLES AT EACH STEP, THE COEFFICIENTS OF ALL THE VARIABLES ARE INCREASED IN PROPORTION TO THEIR CORRELATION WITH THE RESIDUAL. THEN AT EACH STEP, THE VARIABLE MOST HIGHLY CORRELATED WITH THE RESIDUAL IS INCLUDED INTO THE MODEL. THIS PROCEDURE CONTINUES UNTIL ALL VARIABLES ARE IN THE MODEL. THE ALGORITHM CAN BE USED FOR LEAST SQUARES REGRESSION, AS WELL AS FOR LASSO-TYPE REGRESSIONS. WHEN THE TARGET IS SPARSE, IT IS POSSIBLE TO GET AN EXACT SOLUTION IN A FINITE NUMBER OF STEPS.
class LEAST_ANGLE_REGRESSION:
    # INITIALIZES THE LEAST ANGLE REGRESSION MODEL.
    def __init__(self):
        pass

    # FIT(): FITS THE LEAST ANGLE REGRESSION MODEL TO THE TRAINING DATA.
    def FIT(self, X, Y):
        pass

    # TRANSFORM(): TRANSFORMS THE DATA TO THE LEAST ANGLE REGRESSION MODEL.
    def TRANSFORM(self, X):
        pass