import numpy as np

# TODO

# ORDINARY_LEAST_SQUARES_REGRESSION: IMPLEMENTATION OF ORDINARY LEAST SQUARES REGRESSION. ORDINARY LEAST SQUARES (OLS) REGRESSION IS A METHOD FOR ESTIMATING THE UNKNOWN PARAMETERS IN A LINEAR REGRESSION MODEL. OLS REGRESSION FINDS THE PARAMETER VALUES THAT MINIMIZE THE SUM OF THE SQUARED DIFFERENCES BETWEEN THE OBSERVED AND PREDICTED VALUES.
class ORDINARY_LEAST_SQUARES_REGRESSION:
    # INITIALIZES THE ORDINARY LEAST SQUARES REGRESSION MODEL.
    def __init__(self):
        pass

    # FIT(): FITS THE ORDINARY LEAST SQUARES REGRESSION MODEL TO THE TRAINING DATA.
    def FIT(self, X, Y):
        pass

    # TRANSFORM(): TRANSFORMS THE DATA TO THE ORDINARY LEAST SQUARES REGRESSION MODEL.
    def TRANSFORM(self, X):
        pass