import numpy as np

# TODO

# STEPWISE_REGRESSION: IMPLEMENTS STEPWISE REGRESSION. STEPWISE REGRESSION IS A METHOD OF FITTING REGRESSION MODELS IN WHICH THE CHOICE OF PREDICTOR VARIABLES IS CARRIED OUT BY AN AUTOMATIC PROCEDURE. IN EACH STEP, A VARIABLE IS CONSIDERED FOR ADDITION TO OR SUBTRACTION FROM THE SET OF PREDICTORS BASED ON SOME PREDETERMINED CRITERION. USUALLY, THE CRITERION IS THE MAXIMIZATION OF AN ESTIMATED MEASURE OF PREDICTIVE VALIDITY. THE PROCEDURE IS CONTINUED UNTIL NO FURTHER IMPROVEMENT IS OBTAINED. STEPWISE REGRESSION IS A GENERALIZATION OF FORWARD SELECTION AND BACKWARD ELIMINATION. IT IS ALSO KNOWN AS STEPWISE VARIABLE SELECTION.
class STEPWISE_REGRESSION:
    # INITIALIZES THE STEPWISE REGRESSION MODEL.
    def __init__(self):
        pass

    # FIT(): FITS THE STEPWISE REGRESSION MODEL TO THE TRAINING DATA.
    def FIT(self, X, Y):
        pass

    # TRANSFORM(): TRANSFORMS THE DATA TO THE STEPWISE REGRESSION MODEL.
    def TRANSFORM(self, X):
        pass