# CSP: DEFINES A REPRESENTATION OF A CONSTRAINT SATISFACTION PROBLEM. THE CSP IS DEFINED BY ITS VARIABLES, DOMAINS, NEIGHBORS, CONSTRAINTS.
class CSP:
    # INITIALIZE THE CSP OBJECT AND DEFINES THE NEIGHBORS OF EACH VARIABLE.
    def __init__(self, VARIABLES, DOMAINS, CONSTRAINTS):
        self.VARIABLES = VARIABLES # LIST OF VARIABLES
        self.DOMAINS = DOMAINS # DICTIONARY OF DOMAINS: THE KEYS OF THE DICTIONARY ARE THE VARIABLES. THE VALUE OF EACH KEY IN THE DICTIONARY IS THE LIST OF VALUES OF THAT VARIABLE. THE VALUES OF A VARIABLE ARE THE VALUES THAT THE VARIABLE CAN TAKE.
        self.CONSTRAINTS = CONSTRAINTS # LIST OF CONSTRAINTS: THE CONSTRAINT VARIABLE IS DEFINED BY A LISTS OF TWO TUPLES (PAIRS). EACH TUPLE REPRESENTS A PAIR OF VARIABLES THAT MUST SATISFY THE CONSTRAINT. THE CONSTRAINT IS SATISFIED IF THE PAIR DOES NOT HAVE THE SAME VALUE.
        self.NEIGHBORS = {} # DICTIONARY OF NEIGHBORS: THE KEY OF THE DICTIONARY IS THE VARIABLE. THE VALUE OF THE DICTIONARY IS THE LIST OF NEIGHBORS OF THE VARIABLE. THE NEIGHBORS OF A VARIABLE ARE THE VARIABLES THAT SHARE A CONSTRAINT WITH THE VARIABLE.
        for VARIABLE in self.VARIABLES: # FOR EACH VARIABLE, FIND THE NEIGHBORS OF THE VARIABLE.
            self.NEIGHBORS[VARIABLE] = [] # INITIALIZE THE LIST OF NEIGHBORS OF THE VARIABLE.
            for CONSTRAINT in self.CONSTRAINTS: # FOR EACH CONSTRAINT, FIND THE NEIGHBORS OF THE VARIABLE.
                if VARIABLE in CONSTRAINT: # IF THE VARIABLE IS INVOLVED IN THE CONSTRAINT, FIND THE NEIGHBORS OF THE VARIABLE.
                    for VARIABLE_2 in CONSTRAINT: # FOR EACH VARIABLE INVOLVED IN THE CONSTRAINT, FIND THE NEIGHBORS OF THE VARIABLE.
                        if VARIABLE_2 != VARIABLE: # IF THE THEY ARE NOT THE SAME VARIABLE, ADD THE VARIABLE TO THE LIST OF NEIGHBORS OF THE VARIABLE.
                            self.NEIGHBORS[VARIABLE].append(VARIABLE_2) # ADD THE VARIABLE TO THE LIST OF NEIGHBORS OF THE VARIABLE.