"""
NORMALIZATION.

NORMALIZATION IS THE PROCESS OF CONVERTING NUMERICAL DATA TO A STANDARD RANGE OF VALUES.
THIS RANGE IS TYPICALLY BETWEEN [0, 1] OR [-1, 1]. THE EQUATION FOR NORMALIZATION IS
X_NORM = (X - X_MIN)/(X_MAX - X_MIN) WHERE X_NORM IS THE NORMALIZED VALUE, X IS THE
VALUE, X_MIN IS THE MINIMUM VALUE WITHIN THE COLUMN OR LIST OF DATA, AND X_MAX IS THE
MAXIMUM VALUE WITHIN THE COLUMN OR LIST OF DATA. NORMALIZATION IS USED TO SPEED UP THE
TRAINING OF DATA AND PUT ALL OF THE DATA ON A SIMILAR SCALE. THIS IS USEFUL BECAUSE
VARIANCE IN THE RANGE OF VALUES OF A DATASET CAN HEAVILY IMPACT OPTIMIZATION
(PARTICULARLY GRADIENT DESCENT).

STANDARDIZATION IS THE PROCESS OF CONVERTING NUMERICAL DATA TO A NORMALLY DISTRIBUTED
RANGE OF VALUES. THIS RANGE WILL HAVE A MEAN OF 0 AND STANDARD DEVIATION OF 1. THIS IS
ALSO KNOWN AS Z-SCORE NORMALIZATION. THE EQUATION FOR STANDARDIZATION IS
X_STD = (X - MU)/(SIGMA) WHERE MU IS THE MEAN OF THE COLUMN OR LIST OF VALUES AND SIGMA
IS THE STANDARD DEVIATION OF THE COLUMN OR LIST OF VALUES.

CHOOSING BETWEEN NORMALIZATION & STANDARDIZATION IS MORE OF AN ART OF A SCIENCE, BUT IT
IS OFTEN RECOMMENDED TO RUN EXPERIMENTS WITH BOTH TO SEE WHICH PERFORMS BETTER.
ADDITIONALLY, A FEW RULES OF THUMB ARE:
    1. GAUSSIAN (NORMAL) DISTRIBUTIONS WORK BETTER WITH STANDARDIZATION;
    2. NON-GAUSSIAN (NON-NORMAL) DISTRIBUTIONS WORK BETTER WITH NORMALIZATION;
    3. IF A COLUMN OR LIST OF VALUES HAS EXTREME VALUES/OUTLIERS, USE STANDARDIZATION.
"""
from statistics import mean, stdev

def NORMALIZATION(DATA: list, N_DIGITS: int = 3) -> list:
    """
    RETURN A NORMALIZED LIST OF VALUES.

    PARAMS
    ------
    DATA: A LIST OF VALUES TO NORMALIZE
    N_DIGITS: THE NUMBER OF DIGITS TO ROUND TO (DEFAULT: 3)

    RETURNS
    -------
    A LIST OF NORMALIZED VALUES (ROUNDED TO N_DIGITS DECIMAL PLACES)
    """
    X_MIN = min(DATA) # GET MINIMUM VALUE
    X_MAX = max(DATA) # GET MAXIMUM VALUE
    return [round((X - X_MIN) / (X_MAX - X_MIN), N_DIGITS) for X in DATA] # CALCULATE NORMALIZED VALUES

def STANDARDIZATION(DATA: list, N_DIGITS: int = 3) -> list:
    """
    RETURN A STANDARDIZED LIST OF VALUES.

    PARAMS
    ------
    DATA: A LIST OF VALUES TO STANDARDIZE
    N_DIGITS: THE NUMBER OF DIGITS TO ROUND TO (DEFAULT: 3)

    RETURNS
    -------
    RETURNS A LIST OF STANDARDIZED VALUES (ROUNDED TO N_DIGITS DECIMAL PLACES)
    """
    MU = mean(DATA) # GET MEAN
    SIGMA = stdev(DATA) # GET STANDARD DEVIATION
    return [round((X - MU) / (SIGMA), N_DIGITS) for X in DATA] # CALCULATE STANDARDIZED VALUES