import numpy as np

# LINEAR_REGRESSION: CLASS THAT IMPLEMENTS THE LINEAR REGRESSION MODEL
class LINEAR_REGRESSION():
    # INITIALIZES THE LINEAR REGRESSION MODEL
    def __init__(self, LEARNING_RATE, EPOCHS):
        self.LEARNING_RATE = LEARNING_RATE # LEARNING RATE: IT'S THE HYPERPARAMETER THAT CORRESPONDS TO THE LEARNING RATE OF THE ALGORITHM.
        self.EPOCHS = EPOCHS # NUMBER OF ITERATIONS: IT'S THE HYPERPARAMETER THAT CORRESPONDS TO THE NUMBER OF ITERATIONS THAT THE ALGORITHM PASS THROUGH THE TRAINING DATA.
        self.WEIGHTS = None # WEIGHTS: IT'S THE PARAMETER THAT CORRESPONDS TO THE WEIGHTS OF THE LINEAR REGRESSION MODEL.
        self.BIAS = None # BIAS: IT'S THE PARAMETER THAT CORRESPONDS TO THE BIAS OF THE LINEAR REGRESSION MODEL.
    
    # FIT(): FITS THE LINEAR REGRESSION MODEL TO THE TRAINING DATA
    def FIT(self, X, Y):
        # INITIALIZES THE WEIGHTS AND THE BIAS
        self.WEIGHTS = np.zeros(X.shape[1]) # WEIGHTS: IT'S THE PARAMETER THAT CORRESPONDS TO THE WEIGHTS OF THE LINEAR REGRESSION MODEL.
        self.BIAS = 0 # BIAS: IT'S THE PARAMETER THAT CORRESPONDS TO THE BIAS OF THE LINEAR REGRESSION MODEL.
        # IMPLEMENTS THE GRADIENT DESCENT ALGORITHM
        for _ in range(self.EPOCHS): # FOR EACH ITERATION
            PREDICTIONS = self.PREDICT(X) # CALCULATES THE PREDICTIONS OF THE LINEAR REGRESSION MODEL
            # CALCULATES THE DERIVATIVES OF THE WEIGHTS AND THE BIAS
            WEIGHTS_DERIVATIVE = -(2/X.shape[0]) * np.dot(X.T, (Y - PREDICTIONS)) # WEIGHTS_DERIVATIVE: IT'S THE DERIVATIVE OF THE WEIGHTS.
            BIAS_DERIVATIVE = -(2/X.shape[0]) * np.sum(Y - PREDICTIONS) # BIAS_DERIVATIVE: IT'S THE DERIVATIVE OF THE BIAS.
            # UPDATES THE WEIGHTS AND THE BIAS
            self.WEIGHTS -= self.LEARNING_RATE * WEIGHTS_DERIVATIVE
            self.BIAS -= self.LEARNING_RATE * BIAS_DERIVATIVE

    # PREDICT(): RETURNS THE PREDICTIONS OF THE LINEAR REGRESSION MODEL
    def PREDICT(self, X):
        return np.dot(X, self.WEIGHTS) + self.BIAS # RETURNS THE PREDICTIONS OF THE LINEAR REGRESSION MODEL