name: CREATE/UPDATE/IMPROVE
about: REQUEST A FEATURE, SHARE AN IDEA, OR MAKE A SUGGESTION
title: "[CREATE/UPDATE/IMPROVE]"
labels: [CREATE/UPDATE/IMPROVE]
assignees: pmfs1
body:
- type: textarea
  attributes:
    label: Description
    description: *Describe the solution you'd like; or, if that's not the case, the feature itself. Meaning, a clear and concise description of what you want to happen, and of what the suggestion is.*
    render: markdown
  validations:
    required: true
- type: textarea
  attributes:
    label: Alternatives
    description: *Describe alternatives you've considered. There's never too much information.*
    render: markdown
  validations:
    required: true
- type: textarea
  attributes:
    label: Additional Context
    description: *If you feel the need to add any additional context about the feature(s), do it here. This can also be a place to leave notes you might find important. You can also leave screenshots or examples here.*
    render: markdown
  validations:
    required: false
- type: markdown
  attributes:
    value: "*(If you link a development branch to this issue, use the prefix `build-` to uniquely identity it to this category.)*"