name: FIX/REVIEW
description: REQUEST A FIX OR REVIEW; REPORT A BUG
title: "[FIX/REVIEW]"
labels: [FIX/REVIEW]
assignees:
  - pmfs1
body:
  - type: textarea
    attributes:
      label: "Current/Expected Behaviour"
      description: "*Here is where you describe what the software is doing and what it should be doing instead. This section helps the developers understand the problem and how to reproduce it. You should write this section in clear and concise language, using steps, screenshots, or videos if possible. You should also include any relevant information about your system, such as operating system, browser, or device.*"
      render: markdown
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Additional Context"
      description: "*If you feel the need to add any additional context about the feature(s), do it here. This can also be a place to leave notes you might find important.*"
      render: markdown
    validations:
      required: true
  - type: markdown
    attributes:
      value: "> *(If you link a development branch to this issue, use the prefix `patch-` to uniquely identity it to this category.)*"