name: FIX/REVIEW
description: REQUEST A FIX OR REVIEW; REPORT A BUG
title: "[FIX/REVIEW]"
labels: [FIX/REVIEW]
assignees:
  - pmfs1
body:
  - type: textarea
    attributes:
      label: "Current/Expected Behaviour"
      description: "*A clear and concise description of what the bug is, and of what you're experiencing. As well, of what you expected to happen and where it went wrong.*"
      render: markdown
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Additional Context"
      description: "*If you feel the need to add any additional context about the problem, do it here. This can also be a place to leave notes you might find important.*"
      render: markdown
    validations:
      required: false
  - type: markdown
    attributes:
      value: "*(If you link a development branch to this issue, use the prefix `patch-` to uniquely identity it to this category.)*"