# BREAKOUT_METHOD(): ALSO KNOWN AS "CONSTRAINT WEIGHTING"; RUNS THE BREAKOUT METHOD IN ORDER TO FIND A SOLUTION TO THE CONSTRAINT SATISFACTION PROBLEM. RETURNS FALSE IF AN INCONSISTENCY IS FOUND, OTHERWISE RETURNS TRUE.
def BREAKOUT_METHOD():
    pass

# CONSTRAINT_WEIGHTING(): ALSO KNOWN AS "BREAKOUT METHOD"; RUNS THE BREAKOUT METHOD IN ORDER TO FIND A SOLUTION TO THE CONSTRAINT SATISFACTION PROBLEM. RETURNS FALSE IF AN INCONSISTENCY IS FOUND, OTHERWISE RETURNS TRUE.
def CONSTRAINT_WEIGHTING():
    pass