import numpy as np
from autograd import elementwise_grad


class REGULARIZER:
    """BASE CLASS FOR REGULARIZERS"""

    def __init__(self, C=0.01):
        """INITIALIZE A REGULARIZER.

        PARAMETERS
        ----------
        C : FLOAT
            REGULARIZATION STRENGTH.
        """
        self.C = C  # SET REGULARIZATION STRENGTH

    def __PENALTY__(self, WEIGHTS):
        """COMPUTE THE PENALTY FOR A SET OF WEIGHTS."""
        raise NotImplementedError()  # RAISE A NOT IMPLEMENTED ERROR

    def __GRAD__(self, WEIGHTS):
        """COMPUTE THE GRADIENT OF THE PENALTY FOR A SET OF WEIGHTS."""
        return elementwise_grad(self.__PENALTY__, WEIGHTS)  # RETURN THE RESULT OF CALLING THE __GRAD__ FUNCTION WITH ARGUMENT WEIGHTS

    def __call__(self, WEIGHTS):
        """COMPUTE THE PENALTY AND ITS GRADIENT FOR A SET OF WEIGHTS."""
        return elementwise_grad(self.__PENALTY__, WEIGHTS)  # RETURN THE RESULT OF CALLING THE __GRAD__ FUNCTION WITH ARGUMENT WEIGHTS


class L1(REGULARIZER):
    """L1 REGULARIZER."""

    def __PENALTY__(self, WEIGHTS):
        """COMPUTE THE L1 PENALTY FOR A SET OF WEIGHTS."""
        return self.C * np.abs(WEIGHTS)  # RETURN THE PRODUCT OF THE REGULARIZATION STRENGTH AND THE ABSOLUTE VALUE OF THE WEIGHTS


class L2(REGULARIZER):
    """L2 REGULARIZER."""

    def __PENALTY__(self, WEIGHTS):
        """COMPUTE THE L2 PENALTY FOR A SET OF WEIGHTS."""
        return self.C * WEIGHTS ** 2  # RETURN THE PRODUCT OF THE REGULARIZATION STRENGTH AND THE SQUARE OF THE WEIGHTS


class ELASTIC_NET(REGULARIZER):
    """ELASTIC NET REGULARIZER: A MIXTURE OF L1 AND L2 REGULARIZERS."""

    def __PENALTY__(self, WEIGHTS):
        """COMPUTE THE ELASTIC NET PENALTY FOR A SET OF WEIGHTS."""
        return 0.5 * self.C * WEIGHTS ** 2 + (1.0 - self.C) * np.abs(
            WEIGHTS)  # RETURN THE SUM OF THE PRODUCT OF HALF THE REGULARIZATION STRENGTH AND THE SQUARE OF THE WEIGHTS AND THE PRODUCT OF ONE MINUS THE REGULARIZATION STRENGTH AND THE ABSOLUTE VALUE OF THE WEIGHTS
