# DECISION_TREE.NODE: CLASS THAT IMPLEMENTS A NODE OF A DECISION TREE
class NODE:
    # INITIALIZES THE NODE OF A DECISION TREE
    def __init__(self, FEATURE=None, THRESHOLD=None, LEFT=None, RIGHT=None, *, VALUE=None):
        self.FEATURE = FEATURE # FEATURE: IT'S THE FEATURE THAT THE NODE USES TO MAKE A DECISION.
        self.THRESHOLD = THRESHOLD # THRESHOLD: IT'S THE THRESHOLD THAT THE NODE USES TO MAKE A DECISION.
        self.LEFT = LEFT # LEFT: IT'S THE LEFT CHILD OF THE NODE.
        self.RIGHT = RIGHT # RIGHT: IT'S THE RIGHT CHILD OF THE NODE.
        self.VALUE = VALUE # VALUE: IT'S THE VALUE OF THE NODE.

    # IS_LEAF_NODE(): METHOD THAT CHECKS IF THE NODE IS A LEAF NODE
    def IS_LEAF_NODE(self):
        return self.VALUE is not None # RETURNS IF THE NODE IS A LEAF NODE; TRUE OR FALSE