# BETA_BINOMIAL_DISTRIBUTION: IMPLEMENTATION OF BETA BINOMIAL DISTRIBUTION. THE BETA-BINOMIAL DISTRIBUTION, WHICH DESCRIBES THE NUMBER OF SUCCESSES IN A SERIES OF INDEPENDENT YES/NO EXPERIMENTS WITH HETEROGENEITY IN THE SUCCESS PROBABILITY.
class BETA_BINOMIAL_DISTRIBUTION:
    pass