# BINOMIAL_DISTRIBUTION [STATIC]: IMPLEMENTATION OF BINOMIAL DISTRIBUTION. THE BINOMIAL DISTRIBUTION, WHICH DESCRIBES THE NUMBER OF SUCCESSES IN A SERIES OF INDEPENDENT YES/NO EXPERIMENTS ALL WITH THE SAME PROBABILITY OF SUCCESS.
class BINOMIAL_DISTRIBUTION:
    pass