# DEGENERATE_DISTRIBUTION: IMPLEMENTATION OF DEGENERATE DISTRIBUTION. THE DEGENERATE DISTRIBUTION AT X0, WHERE X IS CERTAIN TO TAKE THE VALUE X0. THIS DOES NOT LOOK RANDOM, BUT IT SATISFIES THE DEFINITION OF RANDOM VARIABLE. THIS IS USEFUL BECAUSE IT PUTS DETERMINISTIC VARIABLES AND RANDOM VARIABLES IN THE SAME FORMALISM.
class DEGENERATE_DISTRIBUTION:
    pass