# DISCRETE_UNIFORM_DISTRIBUTION: IMPLEMENTATION OF DISCRETE UNIFORM DISTRIBUTION. THE DISCRETE UNIFORM DISTRIBUTION, WHERE ALL ELEMENTS OF A FINITE SET ARE EQUALLY LIKELY. THIS IS THE THEORETICAL DISTRIBUTION MODEL FOR A BALANCED COIN, AN UNBIASED DIE, A CASINO ROULETTE, OR THE FIRST CARD OF A WELL-SHUFFLED DECK.
class DISCRETE_UNIFORM_DISTRIBUTION:
    pass