# HYPERGEOMETRIC_DISTRIBUTION: IMPLEMENTATION OF HYPERGEOMETRIC DISTRIBUTION. THE HYPERGEOMETRIC DISTRIBUTION, WHICH DESCRIBES THE NUMBER OF SUCCESSES IN THE FIRST M OF A SERIES OF N CONSECUTIVE YES/NO EXPERIMENTS, IF THE TOTAL NUMBER OF SUCCESSES IS KNOWN. THIS DISTRIBUTION ARISES WHEN THERE IS NO REPLACEMENT.
class HYPERGEOMETRIC_DISTRIBUTION:
    pass
