# NEGATIVE_HYPERGEOMETRIC_DISTRIBUTION: IMPLEMENTATION OF NEGATIVE HYPERGEOMETRIC DISTRIBUTION. THE NEGATIVE HYPERGEOMETRIC DISTRIBUTION, A DISTRIBUTION WHICH DESCRIBES THE NUMBER OF ATTEMPTS NEEDED TO GET THE NTH SUCCESS IN A SERIES OF YES/NO EXPERIMENTS WITHOUT REPLACEMENT.
class NEGATIVE_HYPERGEOMETRIC_DISTRIBUTION:
    pass