# POISSON_BINOMIAL_DISTRIBUTION: IMPLEMENTATION OF POISSON BINOMIAL DISTRIBUTION. THE POISSON BINOMIAL DISTRIBUTION, WHICH DESCRIBES THE NUMBER OF SUCCESSES IN A SERIES OF INDEPENDENT YES/NO EXPERIMENTS WITH DIFFERENT SUCCESS PROBABILITIES.
class POISSON_BINOMIAL_DISTRIBUTION:
    pass
