# RADEMACHER_DISTRIBUTION [STATIC]: IMPLEMENTATION OF RADEMACHER DISTRIBUTION. THE RADEMACHER DISTRIBUTION, WHICH TAKES VALUE 1 WITH PROBABILITY 1/2 AND VALUE −1 WITH PROBABILITY 1/2.
class RADEMACHER_DISTRIBUTION:
    pass