# WALLENIUS_NONCENTRAL_HYPERGEOMETRIC_DISTRIBUTION: IMPLEMENTATION FOR WALLENIUS' NONCENTRAL HYPERGEOMETRIC DISTRIBUTION. WALLENIUS' NONCENTRAL HYPERGEOMETRIC DISTRIBUTION (NAMED AFTER KENNETH TED WALLENIUS) IS A GENERALIZATION OF THE HYPERGEOMETRIC DISTRIBUTION WHERE ITEMS ARE SAMPLED WITH BIAS.
class WALLENIUS_NONCENTRAL_HYPERGEOMETRIC_DISTRIBUTION:
    pass