# DEGENERATE_DISTRIBUTION: IMPLEMENTATION OF DEGENERATE DISTRIBUTION. THE DEGENERATE DISTRIBUTION AT X0, WHERE X IS CERTAIN TO TAKE THE VALUE X0. THIS DOES NOT LOOK RANDOM, BUT IT SATISFIES THE DEFINITION OF RANDOM VARIABLE. THIS IS USEFUL BECAUSE IT PUTS DETERMINISTIC VARIABLES AND RANDOM VARIABLES IN THE SAME FORMALISM.
class DEGENERATE_DISTRIBUTION:
    # PROBABILITY_MASS_FUNCTION [STATIC]: PROBABILITY MASS FUNCTION OF DEGENERATE DISTRIBUTION
    @staticmethod
    def PROBABILITY_MASS_FUNCTION(X: float, K_0: float) -> float:
        return 1 if X == K_0 else 0 # RETURN 1 IF X IS EQUAL TO K_0 ELSE 0
    
    # CUMULATIVE_DISTRIBUTION_FUNCTION [STATIC]: CUMULATIVE DISTRIBUTION FUNCTION OF DEGENERATE DISTRIBUTION
    @staticmethod
    def CUMULATIVE_DISTRIBUTION_FUNCTION(X: float, K_0: float) -> float:
        return 1 if X >= K_0 else 0 # RETURN 1 IF X IS GREATER THAN OR EQUAL TO K_0 ELSE 0