# DEGENERATE_DISTRIBUTION: IMPLEMENTATION OF DEGENERATE DISTRIBUTION. THE DEGENERATE DISTRIBUTION AT X0, WHERE X IS CERTAIN TO TAKE THE VALUE X0. THIS DOES NOT LOOK RANDOM, BUT IT SATISFIES THE DEFINITION OF RANDOM VARIABLE. THIS IS USEFUL BECAUSE IT PUTS DETERMINISTIC VARIABLES AND RANDOM VARIABLES IN THE SAME FORMALISM.
class DEGENERATE_DISTRIBUTION:
    # PROBABILITY_MASS_FUNCTION [STATIC]: IN PROBABILITY AND STATISTICS, A PROBABILITY MASS FUNCTION IS A FUNCTION THAT GIVES THE PROBABILITY THAT A DISCRETE RANDOM VARIABLE IS EXACTLY EQUAL TO SOME VALUE. THE PROBABILITY MASS FUNCTION IS OFTEN THE PRIMARY MEANS OF DEFINING A DISCRETE PROBABILITY DISTRIBUTION, AND SUCH FUNCTIONS EXIST FOR EITHER DISCRETE RANDOM VARIABLES OR CONTINUOUS RANDOM VARIABLES WHOSE CUMULATIVE DISTRIBUTION FUNCTION IS DISCONTINUOUS. THE PROBABILITY MASS FUNCTION IS SOMETIMES ALSO CALLED THE PROBABILITY FUNCTION, OR THE PROBABILITY DISTRIBUTION FUNCTION.
    @staticmethod
    def PROBABILITY_MASS_FUNCTION(X: float, K_0: float) -> float:
        return 1 if X == K_0 else 0 # RETURN 1 IF X IS EQUAL TO K_0 ELSE 0
    
    # CUMULATIVE_DISTRIBUTION_FUNCTION [STATIC]: IN PROBABILITY THEORY AND STATISTICS, THE CUMULATIVE DISTRIBUTION FUNCTION (CDF) OF A REAL-VALUED RANDOM VARIABLE X, OR JUST DISTRIBUTION FUNCTION OF X, EVALUATED AT X, IS THE PROBABILITY THAT X WILL TAKE A VALUE LESS THAN OR EQUAL TO X.
    @staticmethod
    def CUMULATIVE_DISTRIBUTION_FUNCTION(X: float, K_0: float) -> float:
        return 1 if X >= K_0 else 0 # RETURN 1 IF X IS GREATER THAN OR EQUAL TO K_0 ELSE 0