# RADEMACHER_DISTRIBUTION [STATIC]: IMPLEMENTATION OF RADEMACHER DISTRIBUTION. THE RADEMACHER DISTRIBUTION, WHICH TAKES VALUE 1 WITH PROBABILITY 1/2 AND VALUE −1 WITH PROBABILITY 1/2.
class RADEMACHER_DISTRIBUTION:
    # PROBABILITY_MASS_FUNCTION [STATIC]: IN PROBABILITY AND STATISTICS, A PROBABILITY MASS FUNCTION IS A FUNCTION THAT GIVES THE PROBABILITY THAT A DISCRETE RANDOM VARIABLE IS EXACTLY EQUAL TO SOME VALUE. THE PROBABILITY MASS FUNCTION IS OFTEN THE PRIMARY MEANS OF DEFINING A DISCRETE PROBABILITY DISTRIBUTION, AND SUCH FUNCTIONS EXIST FOR EITHER DISCRETE RANDOM VARIABLES OR CONTINUOUS RANDOM VARIABLES WHOSE CUMULATIVE DISTRIBUTION FUNCTION IS DISCONTINUOUS. THE PROBABILITY MASS FUNCTION IS SOMETIMES ALSO CALLED THE PROBABILITY FUNCTION, OR THE PROBABILITY DISTRIBUTION FUNCTION.
    @staticmethod
    def PROBABILITY_MASS_FUNCTION(K: int) -> float:
        if K == 1:  # IF K IS EQUAL TO 1
            return 1 / 2  # RETURN 1 / 2
        elif K == -1:  # IF K IS EQUAL TO -1
            return 1 / 2  # RETURN 1 / 2
        else:  # ELSE
            return 0  # RETURN 0

    # CUMULATIVE_DISTRIBUTION_FUNCTION [STATIC]: IN PROBABILITY THEORY AND STATISTICS, THE CUMULATIVE DISTRIBUTION FUNCTION (CDF) OF A REAL-VALUED RANDOM VARIABLE X, OR JUST DISTRIBUTION FUNCTION OF X, EVALUATED AT X, IS THE PROBABILITY THAT X WILL TAKE A VALUE LESS THAN OR EQUAL TO X.
    @staticmethod
    def CUMULATIVE_DISTRIBUTION_FUNCTION(K: int) -> float:
        if K < -1:  # IF K IS LESS THAN -1
            return 0  # RETURN 0
        elif K >= -1 and K < 1:  # IF K IS GREATER THAN OR EQUAL TO -1 AND LESS THAN 1
            return 1 / 2  # RETURN 1 / 2
        elif K >= 1:  # IF K IS GREATER THAN OR EQUAL TO 1
            return 1  # RETURN 1
        else: # ELSE
            raise ValueError("K IS NOT A VALID VALUE")  # RAISE A VALUE ERROR