name: 'BUILD_RUN_TEST'
on: [ push, pull_request ]
jobs:
  BUILD_RUN_TEST:
    name: 'BUILD_RUN_TEST'
    runs-on: ${{ (matrix.language == 'swift' && 'macos-latest') || 'ubuntu-latest' }}
    timeout-minutes: ${{ (matrix.language == 'swift' && 120) || 360 }}
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      matrix: 
        LANGUAGE: [ "python" ]
      fail-fast: true
    steps:
    - name: 'CHECKOUT'
      uses: actions/checkout@v3
    - name: 'EXECUTE DEPENDENCY REVIEW'
      uses: actions/dependency-review-action@v2
      if: github.event.pull_request.base.ref == 'develop'
    - name: 'SET-UP PYTHON'
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: 'SET-UP DEPENDENCIES'
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        if [ -f REQUIREMENTS.txt ]; then pip install -r REQUIREMENTS.txt; else pip install numpy autograd; fi
    - name: 'INITIALIZE'
      uses: github/codeql-action/init@v2
      with:
        languages: ${{ matrix.LANGUAGE }}
        queries: security-extended,security-and-quality
    - name: 'BUILD (FOR TEST PURPOSES)'
      uses: github/codeql-action/autobuild@v2
    - name: 'ANALYZE (SECURITY)'
      uses: github/codeql-action/analyze@v2
      with:
        category: "/language:${{matrix.language}}"
    - name: 'ANALYZE (QUALITY)'
      run: | 
          pylint --disable=invalid-name,missing-docstring,missing-function-docstring,missing-class-docstring,missing-module-docstring,missing-final-newline,line-too-long,too-many-nested-blocks,too-many-instance-attributes,too-many-arguments,trailing-whitespace,unnecessary-pass,too-many-locals,too-few-public-methods,similarities --fail-under 9.75 $(git ls-files '*.py')