name: 'BUILD_RUN_TEST_PUBLISH'
on: [ push, pull_request, release ]
permissions:
  contents: read
jobs:
  BUILD_RUN_TEST_PUBLISH:
    name: 'BUILD_RUN_TEST_PUBLISH'
    runs-on: ${{ (matrix.language == 'swift' && 'macos-latest') || 'ubuntu-latest' }}
    timeout-minutes: ${{ (matrix.language == 'swift' && 120) || 360 }}
    permissions:
      actions: read
      contents: read
      security-events: write
      packages: write
    strategy:
      matrix: 
        LANGUAGE: [ "python" ]
    steps:
    - name: 'PERMISSIONS CONFIG'
      uses: GitHubSecurityLab/actions-permissions/monitor@v1
      with:
        config: ${{ vars.PERMISSIONS_CONFIG }}
    - name: 'CHECKOUT'
      uses: actions/checkout@v3
    - name: 'SET-UP PYTHON'
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: 'SET-UP DEPENDENCIES'
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        if [ -f REQUIREMENTS.txt ]; then pip install -r REQUIREMENTS.txt; fi
    - name: 'INITIALIZE'
      uses: github/codeql-action/init@v2
      with:
        languages: ${{ matrix.LANGUAGE }}
        queries: security-extended,security-and-quality
    - name: 'BUILD (FOR TEST PURPOSES)'
      uses: github/codeql-action/autobuild@v2
    - name: 'ANALYZE (SECURITY)'
      uses: github/codeql-action/analyze@v2
      with:
        category: "/language:${{matrix.language}}"
    - name: 'ANALYZE (QUALITY)'
      run: | 
          pylint --disable=invalid-name,missing-docstring,missing-function-docstring,missing-class-docstring,missing-module-docstring,missing-final-newline,line-too-long,too-many-nested-blocks,too-many-instance-attributes,too-many-arguments,trailing-whitespace,unnecessary-pass,too-many-locals,too-few-public-methods,similarities --fail-under=9.75 $(git ls-files '*.py')
    - name: 'AUTHENTICATE'
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
    - name: 'PUBLISH'
      if: github.event_name == 'release'
      run: |
        docker build . --file Dockerfile --tag "${{ github.repository }}" --label "runnumber=${GITHUB_RUN_ID}"
        IMAGE_ID="ghcr.io/${{ github.repository }}"
        IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
        VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
        [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
        [ "$VERSION" == "develop" ] && VERSION=latest
        echo IMAGE_ID=$IMAGE_ID
        echo VERSION=$VERSION
        docker tag "${{ github.repository }}" $IMAGE_ID:$VERSION
        docker push $IMAGE_ID:$VERSION