name: "DEFENDER_FOR_DEVOPS"
on: [ push, pull_request ]
permissions:
  contents: read
jobs:
  DEFENDER_FOR_DEVOPS:
    name: 'DEFENDER FOR DEVOPS'
    permissions:
      contents: read
      security-events: write
      actions: read
    runs-on: windows-latest
    steps:
    - name: 'CHECKOUT'
      uses: actions/checkout@v3
    - name: 'SET-UP DOTNET PLATFORM'
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          5.0.x
          6.0.x
    - name: 'RUN'
      uses: microsoft/security-devops-action@v1.6.0
      id: msdo
    - name: 'UPLOAD RESULTS'
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: ${{ steps.msdo.outputs.sarifFile }}
