name: 'DEPENDENCY_REVIEW'
on: [ pull_request ]
permissions:
  contents: read
jobs:
  DEPENDENCY_REVIEW:
    name: 'DEPENDENCY REVIEW'
    runs-on: ubuntu-latest
    steps:
      - name: 'CHECKOUT'
        uses: actions/checkout@v3
      - name: 'EXECUTE DEPENDENCY REVIEW'
        uses: actions/dependency-review-action@v2
