name: 'DIAGRAM'
on: [ workflow_dispatch, push ]
jobs:
  DIAGRAM:
    name: 'DIAGRAM'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read
    steps:
      - name: 'CHECKOUT'
        uses: actions/checkout@v3
      - name: 'SET-UP GPG'
        uses: crazy-max/ghaction-import-gpg@v5.3.0
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
      - name: 'UPDATE'
        uses: githubocto/repo-visualizer@main
        with:
          excluded_paths: "ignore,.github"
