name: 'PUBLISH'
on:
  push:
    branches: [ 'develop' ]
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  PUBLISH:
    name: 'PUBLISH'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: 'CHECKOUT'
        uses: actions/checkout@v3
      - name: 'AUTHENTICATE'
        uses: docker/login-action@v2.2.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: 'EXTRACT METADATA'
        id: METADATA
        uses: docker/metadata-action@v4.6.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: 'BUILD & PUSH'
        uses: docker/build-push-action@v4.1.1
        with:
          context: .
          push: true
          tags: ${{ steps.METADATA.outputs.tags }}
          labels: ${{ steps.METADATA.outputs.labels }}
